# Generated by Django 4.2.1 on 2024-04-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='university_id',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='sertificate',
            name='university_id',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Sertificate',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
