# Generated by Django 4.2.1 on 2024-04-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='university_id',
        ),
        migrations.RemoveField(
            model_name='sertificate',
            name='university_id',
        ),
        migrations.AddField(
            model_name='university',
            name='facultities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.faculties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='sertificate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.sertificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.city'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.payment'),
        ),
    ]
